services:
  postgres:
    image: postgres:14-alpine
    container_name: skillhub-postgres
    environment:
      POSTGRES_USER: skillhub
      POSTGRES_PASSWORD: strong_password
      POSTGRES_DB: skillhub_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
